# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Yanwen Sun
tagline:          'Happy coding, happy blogging.'
description:      'Start here,<br>make a difference.'
url:              http://www.sunyanwen.top/

author:
  name:           'Yanwen Sun'
  email:          sywhit@hotmail.com

paginate:         3
paginate_path: "blog/page:num"

gems: [jekyll-paginate]

# custom vars
since:                  2015
google_analytics:       UA-63207330-1
emailme:                mailto:sywhit@hotmail.com
github:
  repo:                 https://github.com/hitersyw/hitersyw.github.io/
version:                Feb.7.2020
orcid_username:         0000-0003-4281-5120
researcherid_username:  R-3094-2018
#googlescholar_username: fWi5tx8AAAAJ&hl
researchgate_username:  Sun Yanwen
#linkedin_username:      zrwang
github_username:        hitersyw
share_pdf:              no
share_video:            no
# facebook_username: zrwang.cuhk
# google_plus_username: 115306810481973645007
# twitter_username: wangzerui
# instagram_username: wzr.mavericker
# cv_chn: yes